#!/bin/sh
c=1
for option in "" "mesh:nz=20"
do
    if ! ./fastdiff $option > runtest.$c.log
    then
	cat runtest.$c.log
	echo " => Test failed"
	exit 1
    else
	tail runtest.$c.log
    fi
    c=$(expr $c + 1)
done

echo " => No error reported"
exit 0
